"""Generate the blurred previews shown while each photo downloads.

    python -I scripts/generate-placeholders.py

Reads every photo master in src/lib/assets/images and writes src/lib/placeholders.ts: a tiny
(PREVIEW_EDGE px) WebP of each, as a data URI. <MediaFrame placeholder="name"> paints it,
blurred, behind the real image, so a card shows the photo's colours and shapes at once
instead of a flat grey box. Re-run after adding or swapping a photo. Requires Pillow.
"""

import base64
import io
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / 'src' / 'lib' / 'assets' / 'images'
OUT = ROOT / 'src' / 'lib' / 'placeholders.ts'

# Longest edge in pixels: enough for the shapes to read once blurred, a few hundred bytes each
PREVIEW_EDGE = 20


def preview(path: Path) -> str:
	im = ImageOps.exif_transpose(Image.open(path)).convert('RGB')
	im.thumbnail((PREVIEW_EDGE, PREVIEW_EDGE), Image.Resampling.LANCZOS)
	buf = io.BytesIO()
	im.save(buf, 'WEBP', quality=50, method=6)
	return 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode()


if __name__ == '__main__':
	entries = [(path.stem, preview(path)) for path in sorted(IMAGES.glob('*.jpg'))]
	lines = [
		'// Generated by scripts/generate-placeholders.py; do not edit by hand.',
		'// Tiny blurred previews of each photo in src/lib/assets/images, keyed by file name.',
		'export const PLACEHOLDERS: Record<string, string> = {',
		*(f"\t'{name}': '{uri}'," for name, uri in entries),
		'};',
		'',
	]
	OUT.write_text('\n'.join(lines), encoding='utf-8')
	total = sum(len(uri) for _, uri in entries)
	print(f'{OUT.relative_to(ROOT)}  {len(entries)} previews, {total // 1024} KB')
